name: Generate Dependency Graph

on:
  pull_request:

jobs:
  generate_dependency_graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Generate dependency graph
        run: |
          # Get list of modified Markdown files in PR
          files=( ./*.md )

          # Concatenate dependencies for all Markdown files
          all_deps=$(for file in "${files[@]}"; do
              # Output filename being processed
              echo "Processing $file"
              # Get the list of dependencies
              dependencies=$(grep -o 'depends:[0-9]\+' $file | sort | uniq | sed "s/depends://" | awk -v f="${file/.\//NIP-}" '{sub(/\.md/, "", f); print f " -> NIP-" $1}')
              echo "$dependencies"
          done | awk 'NF' | sort -u)

          # Generate the dependency graph and save as a PNG image
          echo "$all_deps" | dot -Tpng -o dependencies.png


      - name: Upload dependency graph
        uses: actions/upload-artifact@v2
        with:
          name: dependency-graph
          path: dependencies.png
