- name: Commit dependency graph to PR branch
  uses: actions/github-script@v4
  with:
    script: |
      const gh = require('@actions/github');
      const octokit = gh.getOctokit(process.env.GITHUB_TOKEN);
      const file = 'dependencies.png';
      const commitMsg = 'chore: update dependency graph';
      const headSha = context.payload.pull_request.head.sha;
      const branchRef = process.env.GITHUB_REF.replace('refs/heads/', '');
      
      octokit.rest.git.getRef({
        owner: context.repo.owner,
        repo: context.repo.repo,
        ref: `heads/${branchRef}`,
      }).then((refData) => {
        const branchSha = refData.data.object.sha;
        return octokit.rest.git.createTree({
          owner: context.repo.owner,
          repo: context.repo.repo,
          base_tree: branchSha,
          tree: [
            {
              path: file,
              mode: '100644',
              type: 'blob',
              content: Buffer.from(require('fs').readFileSync(file)).toString('base64')
            }
          ]
        });
      }).then((treeData) => {
        return octokit.rest.git.createCommit({
          owner: context.repo.owner,
          repo: context.repo.repo,
          message: commitMsg,
          tree: treeData.data.sha,
          parents: [headSha],
          author: {
            name: 'GitHub Actions',
            email: 'actions@github.com'
          },
          committer: {
            name: 'GitHub Actions',
            email: 'actions@github.com'
          }
        });
      }).then(({ data: commit }) => {
        return octokit.rest.git.updateRef({
          owner: context.repo.owner,
          repo: context.repo.repo,
          ref: `heads/${branchRef}`,
          sha: commit.sha,
          force: true
        });
      });
