name: Generate dependency graph

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-dependency-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install graphviz

      - name: Generate dependency graph
        run: |
          # Get list of modified Markdown files in PR
          files=( ./*.md )

          # Concatenate dependencies for all Markdown files
          all_deps=$(for file in "${files[@]}"; do
            # Get the list of dependencies
            dependencies=$(grep -o "depends:[0-9]\+" "$file" | sed -e 's/depends://' | tr -d '[:space:]')
            echo "$dependencies"
          done)

          # Generate the dependency graph and save as a PNG image
          dot -Tpng -o dependencies.png <(echo "$all_deps")

          
      - name: Upload dependency graph images
        uses: actions/upload-artifact@v2
        with:
          name: dependency-graphs
          path: dependencies.png

