name: Generate dependency graph

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-dependency-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install graphviz

      - name: Generate dependency graph
        run: |
          # Get list of modified Markdown files in PR
          files=$(find . -name "*.md")

          # Loop through each modified file
          for file in $files; do
            # Check if the file contains a 'depends:' section
            if grep -q "^## depends:" "$file"; then
              # Get the list of dependencies
              dependencies=$(grep -o "depends:[0-9]+" $file | sed -e 's/depends://' | tr -d '[:space:]')

              # Generate the dependency graph and save as a PNG image
              dot -Tpng -o "${file%%.md}.png" <(echo "$dependencies")
            fi
          done

      - name: Upload dependency graph images
        uses: actions/upload-artifact@v2
        with:
          name: dependency-graphs
          path: |
            $(find . -maxdepth 1 -name '*.png')
